version: '3'
services:
  strapi:
    container_name: cms-store
    image: lwaero/cms-store
    environment:
      - NODE_ENV=production
    env_file: .env.production
    ports:
      - '1337:1337'
    command: 'yarn start'