version: '3'
services:
  strapi:
    container_name: strapi-cms
    build:
      context: .
      dockerfile: Dockerfile
    image: lwaero/strapi-dev:v3.5.3
    env_file: .env.development
    volumes:
      - ./app:/srv/app
      - node_modules:/srv/app/node_modules
    ports:
      - '1337:1337'

volumes:
  node_modules: